### ISSUE TITLE
Install UploadWizard on SEGS Wiki

### ISSUE THREAD

**Issue by broxen** [Segs/Segs.io#42]
## Summary
To facilitate easy file uploads, we should install UploadWizard https://www.mediawiki.org/wiki/Extension:UploadWizard on the SEGS Wiki

Will require
- Make sure that the images directory is writable by your web server.
- Install the ImageMagick libraries and binaries.
- LocalSettings.php configuration

**Comment by ldilley** [comment]
Extension installed and configured.
